Fix migration.
Migration failed with:

```
== 20130922231603 CreateInvitations: migrating ================================
-- create_table(:invitations)
   -> 0.0139s
-- add_index(:invitations, [:proposal_id, :email], {:unique=>true})
   -> 0.0030s
-- add_index(:invitations, :slug, {:unique=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_invitations_on_slug' on table 'invitations' already exists/Users/winston/workspace/cfp-app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:939:in `add_index_options'
/Users/winston/workspace/cfp-app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:476:in `add_index'
/Users/winston/workspace/cfp-app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:665:in `block in method_missing'
...
```

So the solution is to remove `index: true` from the `create_table` dal and just rely on `add_index`.