Proposal.not.has_one :time_slot
Calling this association causes:
ERROR:  column time_slots.proposal_id does not exist (ActiveRecord::StatementInvalid)